### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Dpbm** [Dpbm/seshat#1]
- [x] pass to all screens: width, height
- [x] add icon
- [x] add splash  screen
- [x] get notes from the db
- [x] test home screen without data
- [x] make the edit screen
- [x] make search screen
- [x] change `onChange` event to `Controllers`
- [x] fix naming convention
- [x] make home screen refresh everytime we come back from edit or add screen
- [x] error toast with red text 
- [x] add filters by date (most recent)
- [x] fix card `navigator.push`
- [x] add infinite scroll to home
- [x] fix duplicating on insert
- [x] update autosave on edit screen
- [x] update refresh on home screen when a note is added
- [x] remove `navigation pop` from the build function in edit screen
- [x] fix db for tests
- [x] fix cards width
- [x] fix expands
- [x] test multiple lines on device (fix an amount of lines)
- [x] fix preview
- [x] remove autocorrect
- [x] save when you drag to go back to the previous screen (https://stackoverflow.com/questions/50452710/catch-android-back-button-event-on-flutter)
- [x] add last modified to the db and model
- [x] save dates as int timestamp
- [x] filter by last modified instead of created
- [x] fix interactive selection on add note
- [x] block screen rotation
- [x] share note on WhatsApp 
- [x] fix selection (https://stackoverflow.com/questions/54656386/change-the-highlight-color-of-selected-text)
- [x] add a X to clear the search term
- [x] set icons as widgets
- [x] fix search selection text color
- [x] reload home after coming back from search
- [x] place the "haven't found any notes!!" Message at the top of the component when the keyboard is being used
- [x] change the search sentence to "didn't find any notes"
